# @package _global_
env:
  config:
    mimic_early_termination:
      - mimic_early_termination_key: max_joint_err
        mimic_early_termination_thresh: 1.5
        mimic_early_termination_thresh_on_flat: 1.0
        less_than: False

eval_overrides:
  env:
    config:
      mimic_early_termination: null
