# @package _global_

defaults:
  - base

robot:
  body_names: ['Pelvis', 'Spine', 'Torso', 'Neck', 'Head', 'ShoulderL', 'ArmL', 'ForeArmL', 'HandL', 'ShoulderR', 'ArmR', 'ForeArmR', 'HandR', 'FemurL', 'TibiaL', 'TalusL', 'FootThumbL', 'FootPinkyL', 'FemurR', 'TibiaR', 'TalusR', 'FootThumbR', 'FootPinkyR']
  dof_names: ['Spine_x', 'Spine_y', 'Spine_z', 'Torso_x', 'Torso_y', 'Torso_z', 'Neck_x', 'Neck_y', 'Neck_z', 'Head_x', 'Head_y', 'Head_z', 'L_Shoulder_x', 'L_Shoulder_y', 'L_Shoulder_z', 'L_Elbow_x', 'L_Elbow_y', 'L_Elbow_z', 'ForeArmL_y', 'HandL_x', 'HandL_y', 'HandL_z', 'R_Shoulder_x', 'R_Shoulder_y', 'R_Shoulder_z', 'R_Elbow_x', 'R_Elbow_y', 'R_Elbow_z', 'ForeArmR_y', 'HandR_x', 'HandR_y', 'HandR_z', 'L_Hip_x', 'L_Hip_y', 'L_Hip_z', 'L_Knee', 'L_Ankle_x', 'L_Ankle_y', 'L_Ankle_z', 'L_ToeThumb', 'L_ToePinky', 'R_Hip_x', 'R_Hip_y', 'R_Hip_z', 'R_Knee', 'R_Ankle_x', 'R_Ankle_y', 'R_Ankle_z', 'R_ToeThumb', 'R_ToePinky']
  trackable_bodies_subset: ['Pelvis', 'TalusL', 'TalusR', 'HandL', 'HandR', 'Head']

  dof_obs_size: ${eval:${len:${.dof_body_ids}}*6}
  number_of_actions: 50
  self_obs_max_coords_size: 343

  dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22 ]
  joint_axis: ['xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'y', 'xyz', 'xyz', 'xyz', 'y', 'xyz', 'xyz', 'x', 'xyz', 'x', 'x', 'xyz', 'x', 'xyz', 'x', 'x']

  key_bodies: ['TalusR', 'TalusL', 'HandL', 'HandR']
  non_termination_contact_bodies: ['TalusR', 'TalusL', 'FootThumbR', 'FootThumbL', 'FootPinkyR', 'FootPinkyL']
  right_foot_name: 'TalusR'
  left_foot_name: 'TalusL'
  head_body_name: 'Head'

  asset:
    robot_type: bio_humanoid
    asset_file_name: 'mjcf/bio.xml'
    usd_asset_file_name: "usd/bio.usda"
    filter_ints: null
  sim:
    isaacgym:
      fps: 120
      decimation: 4
      substeps: 1
    isaaclab:
      fps: 240
      decimation: 4

