# @package _global_

defaults:
  - base

robot:
  body_names: ['Pelvis', 'Spine', 'Torso', 'Neck', 'Head', 'ShoulderL', 'ArmL', 'ForeArmL', 'HandL', 'ShoulderR', 'ArmR', 'ForeArmR', 'HandR', 'FemurL', 'TibiaL', 'TalusL', 'FootThumbL', 'FootPinkyL', 'FemurR', 'TibiaR', 'TalusR', 'FootThumbR', 'FootPinkyR']
  dof_names: ['Spine_x', 'Spine_y', 'Spine_z', 'Torso_x', 'Torso_y', 'Torso_z', 'Neck_x', 'Neck_y', 'Neck_z', 'Head_x', 'Head_y', 'Head_z', 'L_Shoulder_x', 'L_Shoulder_y', 'L_Shoulder_z', 'L_Elbow_x', 'L_Elbow_y', 'L_Elbow_z', 'ForeArmL_y', 'HandL_x', 'HandL_y', 'HandL_z', 'R_Shoulder_x', 'R_Shoulder_y', 'R_Shoulder_z', 'R_Elbow_x', 'R_Elbow_y', 'R_Elbow_z', 'ForeArmR_y', 'HandR_x', 'HandR_y', 'HandR_z', 'L_Hip_x', 'L_Hip_y', 'L_Hip_z', 'L_Knee', 'L_Ankle_x', 'L_Ankle_y', 'L_Ankle_z', 'L_ToeThumb', 'L_ToePinky', 'R_Hip_x', 'R_Hip_y', 'R_Hip_z', 'R_Knee', 'R_Ankle_x', 'R_Ankle_y', 'R_Ankle_z', 'R_ToeThumb', 'R_ToePinky']

  trackable_bodies_subset: ['Pelvis', 'TalusL', 'TalusR', 'HandL', 'HandR', 'Head']

  # Observation parameters
  dof_obs_size: ${eval:${len:${.dof_body_ids}}*6}
  number_of_actions: 50

  self_obs_max_coords_size: 343

  # Control parameters
  dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22 ]
  joint_axis: ['xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'y', 'xyz', 'xyz', 'xyz', 'y', 'xyz', 'xyz', 'x', 'xyz', 'x', 'x', 'xyz', 'x', 'xyz', 'x', 'x']
  dof_effort_limits: [
    88.0, 88.0, 88.0,       # Spine 0-2
    88.0, 88.0, 88.0,       # Torso 3-5
    5.0, 5.0, 5.0,          # Neck 6-8
    5.0, 5.0, 5.0,          # Head 9-11
    88.0, 88.0, 88.0,       # L_Shoulder 12-14
    25.0, 25.0, 25.0,       # L_Elbow 15-17
    25.0,                   # ForeArmL_y 18
    5.0, 5.0, 5.0,          # HandL 19-21
    88.0, 88.0, 88.0,       # R_Shoulder 22-24
    25.0, 25.0, 25.0,       # R_Elbow 25-27
    25.0,                   # ForeArmR_y 28
    5.0, 5.0, 5.0,          # HandR 29-31
    88.0, 88.0, 88.0,       # L_Hip 32-34
    139.0,                  # L_Knee 35
    50.0, 50.0, 50.0,       # L_Ankle 36-38
    5.0, 5.0,               # L_Toe 39-40
    88.0, 88.0, 88.0,       # R_Hip 41-43
    139.0,                  # R_Knee 44
    50.0, 50.0, 50.0,       # R_Ankle 45-47
    5.0, 5.0                # R_Toe 48-49
  ]

  dof_vel_limits: [
    32.0, 32.0, 32.0,       # Spine 0-2
    32.0, 32.0, 32.0,       # Torso 3-5
    22.0, 22.0, 22.0,       # Neck 6-8
    22.0, 22.0, 22.0,       # Head 9-11
    37.0, 37.0, 37.0,       # L_Shoulder 12-14
    37.0, 37.0, 37.0,       # L_Elbow 15-17
    37.0,                   # ForeArmL_y 18
    22.0, 22.0, 22.0,       # HandL 19-21
    37.0, 37.0, 37.0,       # R_Shoulder 22-24
    37.0, 37.0, 37.0,       # R_Elbow 25-27
    37.0,                   # ForeArmR_y 28
    22.0, 22.0, 22.0,       # HandR 29-31
    32.0, 32.0, 32.0,       # L_Hip 32-34
    20.0,                   # L_Knee 35
    37.0, 37.0, 37.0,       # L_Ankle 36-38
    22.0, 22.0,             # L_Toe 39-40
    32.0, 32.0, 32.0,       # R_Hip 41-43
    20.0,                   # R_Knee 44
    37.0, 37.0, 37.0,       # R_Ankle 45-47
    22.0, 22.0              # R_Toe 48-49
  ]
  
  dof_armatures: [
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
  ]
  
  dof_joint_frictions: [
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
    0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 
  ]

  key_bodies: ['TalusL', 'TalusR', 'HandL', 'HandR']
  non_termination_contact_bodies: ['TalusR', 'TalusL', 'FootThumbR', 'FootThumbL', 'FootPinkyR', 'FootPinkyL']
  right_foot_name: 'TalusR'
  left_foot_name: 'TalusL'
  head_body_name: 'Head'

  asset:
    robot_type: act_humanoid
    asset_file_name: 'mjcf/bio.xml'
    usd_asset_file_name: "usd/bio.usda"
    self_collisions: False
    default_dof_drive_mode: 3
    collapse_fixed_joints: True
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.
  control:
    control_type: proportional
    use_biased_controller: False  # See default_joint_angles
    map_actions_to_pd_range: True
    action_scale: 1.0
    clamp_actions: 1.0
    stiffness:
      Hip: 100.0
      Knee: 200.0
      Ankle: 20.0
      Torso: 400.0
      Spine: 400.0
      Shoulder: 90.0
      Elbow: 60
      ForeArm: 60
      Hand: 4
      Head: 4
      Neck: 4
      Toe: 4
    damping:
      Hip: 2.5
      Knee: 5.0
      Ankle: 0.2
      Torso: 5.0
      Spine: 5.0
      Shoulder: 2.0
      Elbow: 1.0
      ForeArm: 1.0
      Hand: 0.2
      Head: 0.2
      Neck: 0.2
      Toe: 0.2
  sim:
    isaacgym:
      fps: 120
      decimation: 4
      substeps: 1
    isaaclab:
      fps: 240
      decimation: 4

motion_lib:
  _target_: protomotions.utils.motion_lib.MotionLib
